### ISSUE TITLE
Add function to import images from a folder

### ISSUE THREAD

**Issue by alzyee** [alzyee/Sleep-Schedule#2]
currently the code looks to be setup to pull images from a rtsp stream when an outside process calls a vbs script. Having the code import all pictures from a folder (+sub-folders) seems more generic.

**Comment by g-parki** [comment]
Hi @alzyee, thanks for your interest in this project. As you can tell, this wasn't really written with others in mind, and I don't currently maintain it. But I can help explain what you're looking at.

We were using a Google Nest camera as a baby monitor, and the protocol to tap into its live feed is RTSP.  So any `Streamer()` object is tying directly into the live stream of our camera. As you noted - VBS is only used as the entry point for Windows Task Scheduler to call `sampler.py`, which was done every 10 minutes. This is so we could trend over time "is the baby in the crib or not?"

**Comment by alzyee** [comment]
Thanks for the description.

**Comment by alzyee** [comment]
Rough plan for import process:
1. external process puts pictures in existing ReadingImagesOriginals folder
   1.  This should probably be moved to a dedicated folder but it looks like the site code has this folder hard coded
2. Check if file is in db and skip if it exists
2. reuse code from  sampler and test branch to resize image
3. run model on image
4. insert into db


future plans
* remove path hard coding from web page which would allow
   * the import dir to be pulled from the db where it already exist
   * support subfolders
